/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import javax.swing.JOptionPane;
import modelo.classes.*;
import modelo.interfaces.*;
/**
 *
 * @author Giu
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Veiculo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton_Automovel = new javax.swing.JRadioButton();
        jRadioButton_Aviao = new javax.swing.JRadioButton();
        jRadioButton_Barco = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Resultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel_Vazio = new javax.swing.JPanel();
        jPanel_Automovel = new javax.swing.JPanel();
        jToggleButton_A_Entrar = new javax.swing.JToggleButton();
        jToggleButton_A_Sair = new javax.swing.JToggleButton();
        jToggleButton_A_Ligar = new javax.swing.JToggleButton();
        jToggleButton_A_Desligar = new javax.swing.JToggleButton();
        jToggleButton_A_Acelerar = new javax.swing.JToggleButton();
        jToggleButton_A_Direita = new javax.swing.JToggleButton();
        jToggleButton_A_Esquerda = new javax.swing.JToggleButton();
        jToggleButton_A_Freiar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_Aviao = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton_AV_Entrar = new javax.swing.JToggleButton();
        jToggleButton_AV_Sair = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton_AV_Ligar = new javax.swing.JToggleButton();
        jToggleButton_AV_Desligar = new javax.swing.JToggleButton();
        jToggleButton_AV_Esquerda = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton_AV_Direita = new javax.swing.JToggleButton();
        jToggleButton_AV_Acelerar = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton_AV_Freiar = new javax.swing.JToggleButton();
        jToggleButton_AV_Empurrar = new javax.swing.JToggleButton();
        jToggleButton_AV_Puxar = new javax.swing.JToggleButton();
        jPanel_Barco = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton_B_Entrar = new javax.swing.JToggleButton();
        jToggleButton_B_Sair = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton_B_Ligar = new javax.swing.JToggleButton();
        jToggleButton_B_Desligar = new javax.swing.JToggleButton();
        jToggleButton_B_Esquerda = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton_B_Direita = new javax.swing.JToggleButton();
        jToggleButton_B_Acelerar = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton_B_Freiar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Veiculo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Veiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup_Veiculo.add(jRadioButton_Automovel);
        jRadioButton_Automovel.setText("Automovel");
        jRadioButton_Automovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AutomovelActionPerformed(evt);
            }
        });

        buttonGroup_Veiculo.add(jRadioButton_Aviao);
        jRadioButton_Aviao.setText("Aviao");
        jRadioButton_Aviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AviaoActionPerformed(evt);
            }
        });

        buttonGroup_Veiculo.add(jRadioButton_Barco);
        jRadioButton_Barco.setText("Barco");
        jRadioButton_Barco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_BarcoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_Automovel)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Aviao)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Barco)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Automovel)
                    .addComponent(jRadioButton_Aviao)
                    .addComponent(jRadioButton_Barco))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTextArea_Resultado.setEditable(false);
        jTextArea_Resultado.setBackground(new java.awt.Color(222, 221, 221));
        jTextArea_Resultado.setColumns(20);
        jTextArea_Resultado.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea_Resultado.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Resultado);

        javax.swing.GroupLayout jPanel_VazioLayout = new javax.swing.GroupLayout(jPanel_Vazio);
        jPanel_Vazio.setLayout(jPanel_VazioLayout);
        jPanel_VazioLayout.setHorizontalGroup(
            jPanel_VazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel_VazioLayout.setVerticalGroup(
            jPanel_VazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jPanel_Automovel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Automovel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jToggleButton_A_Entrar.setText("Entrar");
        jToggleButton_A_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_EntrarActionPerformed(evt);
            }
        });

        jToggleButton_A_Sair.setText("Sair");
        jToggleButton_A_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_SairActionPerformed(evt);
            }
        });

        jToggleButton_A_Ligar.setText("Ligar");
        jToggleButton_A_Ligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_LigarActionPerformed(evt);
            }
        });

        jToggleButton_A_Desligar.setText("Desligar");
        jToggleButton_A_Desligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_DesligarActionPerformed(evt);
            }
        });

        jToggleButton_A_Acelerar.setText("Acelerar");
        jToggleButton_A_Acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_AcelerarActionPerformed(evt);
            }
        });

        jToggleButton_A_Direita.setText("Direita");
        jToggleButton_A_Direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_DireitaActionPerformed(evt);
            }
        });

        jToggleButton_A_Esquerda.setText("Esquerda");
        jToggleButton_A_Esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_EsquerdaActionPerformed(evt);
            }
        });

        jToggleButton_A_Freiar.setText("Freiar");
        jToggleButton_A_Freiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_A_FreiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Porta");

        jLabel3.setText("Motor");

        jLabel4.setText("Volante");

        jLabel5.setText("Pedal");

        javax.swing.GroupLayout jPanel_AutomovelLayout = new javax.swing.GroupLayout(jPanel_Automovel);
        jPanel_Automovel.setLayout(jPanel_AutomovelLayout);
        jPanel_AutomovelLayout.setHorizontalGroup(
            jPanel_AutomovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AutomovelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel_AutomovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AutomovelLayout.createSequentialGroup()
                        .addComponent(jToggleButton_A_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_AutomovelLayout.createSequentialGroup()
                        .addGap(0, 166, Short.MAX_VALUE)
                        .addComponent(jToggleButton_A_Esquerda)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_A_Direita, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel5)
                        .addGap(190, 190, 190))
                    .addGroup(jPanel_AutomovelLayout.createSequentialGroup()
                        .addGroup(jPanel_AutomovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_A_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_A_Desligar)
                            .addComponent(jToggleButton_A_Ligar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AutomovelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_AutomovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton_A_Freiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_A_Acelerar))
                .addGap(164, 164, 164))
        );
        jPanel_AutomovelLayout.setVerticalGroup(
            jPanel_AutomovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AutomovelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_A_Entrar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_A_Sair)
                .addGap(31, 31, 31)
                .addComponent(jToggleButton_A_Acelerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AutomovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_A_Esquerda)
                    .addComponent(jToggleButton_A_Direita)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_A_Freiar)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_A_Ligar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_A_Desligar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel_Aviao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Aviao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel6.setText("Cabine");

        jToggleButton_AV_Entrar.setText("Entrar");
        jToggleButton_AV_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_EntrarActionPerformed(evt);
            }
        });

        jToggleButton_AV_Sair.setText("Sair");
        jToggleButton_AV_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_SairActionPerformed(evt);
            }
        });

        jLabel7.setText("Motor");

        jToggleButton_AV_Ligar.setText("Ligar");
        jToggleButton_AV_Ligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_LigarActionPerformed(evt);
            }
        });

        jToggleButton_AV_Desligar.setText("Desligar");
        jToggleButton_AV_Desligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_DesligarActionPerformed(evt);
            }
        });

        jToggleButton_AV_Esquerda.setText("Esquerda");
        jToggleButton_AV_Esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_EsquerdaActionPerformed(evt);
            }
        });

        jLabel8.setText("Manche");

        jToggleButton_AV_Direita.setText("Direita");
        jToggleButton_AV_Direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_DireitaActionPerformed(evt);
            }
        });

        jToggleButton_AV_Acelerar.setText("Acelerar");
        jToggleButton_AV_Acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_AcelerarActionPerformed(evt);
            }
        });

        jLabel9.setText("Alavanca");

        jToggleButton_AV_Freiar.setText("Freiar");
        jToggleButton_AV_Freiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_FreiarActionPerformed(evt);
            }
        });

        jToggleButton_AV_Empurrar.setText("Empurrar");
        jToggleButton_AV_Empurrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_EmpurrarActionPerformed(evt);
            }
        });

        jToggleButton_AV_Puxar.setText("Puxar");
        jToggleButton_AV_Puxar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_AV_PuxarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_AviaoLayout = new javax.swing.GroupLayout(jPanel_Aviao);
        jPanel_Aviao.setLayout(jPanel_AviaoLayout);
        jPanel_AviaoLayout.setHorizontalGroup(
            jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                        .addComponent(jToggleButton_AV_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                        .addGap(0, 135, Short.MAX_VALUE)
                        .addComponent(jToggleButton_AV_Esquerda)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_AV_Direita, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(357, 357, 357))
                    .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                        .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_AV_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_AV_Desligar)
                            .addComponent(jToggleButton_AV_Ligar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(0, 659, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AviaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AviaoLayout.createSequentialGroup()
                        .addComponent(jToggleButton_AV_Empurrar)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AviaoLayout.createSequentialGroup()
                        .addComponent(jToggleButton_AV_Puxar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)))
                .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton_AV_Freiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton_AV_Acelerar)))
                .addGap(164, 164, 164))
        );
        jPanel_AviaoLayout.setVerticalGroup(
            jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_AV_Entrar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_AV_Sair)
                .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                        .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jToggleButton_AV_Acelerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_AviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jToggleButton_AV_Esquerda)
                                    .addComponent(jToggleButton_AV_Direita)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel_AviaoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jToggleButton_AV_Empurrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton_AV_Freiar)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AviaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton_AV_Puxar)
                        .addGap(15, 15, 15)))
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_AV_Ligar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_AV_Desligar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel_Barco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Barco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel10.setText("Subir a Bordo");

        jToggleButton_B_Entrar.setText("Entrar");
        jToggleButton_B_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_EntrarActionPerformed(evt);
            }
        });

        jToggleButton_B_Sair.setText("Sair");
        jToggleButton_B_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_SairActionPerformed(evt);
            }
        });

        jLabel11.setText("Motor");

        jToggleButton_B_Ligar.setText("Ligar");
        jToggleButton_B_Ligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_LigarActionPerformed(evt);
            }
        });

        jToggleButton_B_Desligar.setText("Desligar");
        jToggleButton_B_Desligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_DesligarActionPerformed(evt);
            }
        });

        jToggleButton_B_Esquerda.setText("Esquerda");
        jToggleButton_B_Esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_EsquerdaActionPerformed(evt);
            }
        });

        jLabel12.setText("Timão");

        jToggleButton_B_Direita.setText("Direita");
        jToggleButton_B_Direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_DireitaActionPerformed(evt);
            }
        });

        jToggleButton_B_Acelerar.setText("Acelerar");
        jToggleButton_B_Acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_AcelerarActionPerformed(evt);
            }
        });

        jLabel13.setText("Alavanca");

        jToggleButton_B_Freiar.setText("Freiar");
        jToggleButton_B_Freiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_B_FreiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BarcoLayout = new javax.swing.GroupLayout(jPanel_Barco);
        jPanel_Barco.setLayout(jPanel_BarcoLayout);
        jPanel_BarcoLayout.setHorizontalGroup(
            jPanel_BarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarcoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel_BarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BarcoLayout.createSequentialGroup()
                        .addComponent(jToggleButton_B_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_BarcoLayout.createSequentialGroup()
                        .addGap(0, 153, Short.MAX_VALUE)
                        .addComponent(jToggleButton_B_Esquerda)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton_B_Direita, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(357, 357, 357))
                    .addGroup(jPanel_BarcoLayout.createSequentialGroup()
                        .addGroup(jPanel_BarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_B_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_B_Desligar)
                            .addComponent(jToggleButton_B_Ligar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarcoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_BarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton_B_Freiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_B_Acelerar))
                .addGap(164, 164, 164))
            .addGroup(jPanel_BarcoLayout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BarcoLayout.setVerticalGroup(
            jPanel_BarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarcoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_B_Entrar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_B_Sair)
                .addGap(31, 31, 31)
                .addComponent(jToggleButton_B_Acelerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_B_Esquerda)
                    .addComponent(jToggleButton_B_Direita)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_B_Freiar)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_B_Ligar)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_B_Desligar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel_Automovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanel_Aviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanel_Barco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Vazio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel_Automovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jPanel_Aviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(jPanel_Barco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Vazio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel1.setText("Nome do Veiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_Nome))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_AutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AutomovelActionPerformed
        // TODO add your handling code here:
        jPanel_Automovel.setVisible(true);
        jPanel_Barco.setVisible(false);
        jPanel_Aviao.setVisible(false);
    }//GEN-LAST:event_jRadioButton_AutomovelActionPerformed

    private void jRadioButton_AviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AviaoActionPerformed
        // TODO add your handling code here:
        jPanel_Automovel.setVisible(false);
        jPanel_Barco.setVisible(false);
        jPanel_Aviao.setVisible(true);
    }//GEN-LAST:event_jRadioButton_AviaoActionPerformed

    private void jRadioButton_BarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_BarcoActionPerformed
        // TODO add your handling code here:
        jPanel_Automovel.setVisible(false);
        jPanel_Barco.setVisible(true);
        jPanel_Aviao.setVisible(false);
    }//GEN-LAST:event_jRadioButton_BarcoActionPerformed

    private void jToggleButton_A_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_EntrarActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.entrar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
           
    }//GEN-LAST:event_jToggleButton_A_EntrarActionPerformed

    private void jToggleButton_A_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_SairActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.sair_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_SairActionPerformed

    private void jToggleButton_A_LigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_LigarActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.ligar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_LigarActionPerformed

    private void jToggleButton_A_DesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_DesligarActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.desligar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_DesligarActionPerformed

    private void jToggleButton_A_EsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_EsquerdaActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.automovel_virar_volante_esquerda()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_EsquerdaActionPerformed

    private void jToggleButton_A_DireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_DireitaActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.automovel_virar_volante_direita()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_DireitaActionPerformed

    private void jToggleButton_A_AcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_AcelerarActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.automovel_pisar_pedal_acelerar()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_AcelerarActionPerformed

    private void jToggleButton_A_FreiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_A_FreiarActionPerformed
        // TODO add your handling code here:
        try {
            
           Automovel dados_automovel = new Automovel();
           
           String entrada = "";
           
           if (jRadioButton_Automovel.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_automovel.setNome_do_veiculo(entrada);
            
           String saida_dados_automovel = "Veiculo \n";
           saida_dados_automovel += "Tipo: " + dados_automovel.getTipoDoVeiculo()+ "\n";
           saida_dados_automovel += "Nome: " + dados_automovel.getNome_do_veiculo()+ "\n";
           saida_dados_automovel += "Ação: " + dados_automovel.automovel_pisar_pedal_freiar()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_automovel);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_A_FreiarActionPerformed

    private void jToggleButton_AV_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_EntrarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.entrar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_EntrarActionPerformed

    private void jToggleButton_AV_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_SairActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.sair_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_SairActionPerformed

    private void jToggleButton_AV_LigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_LigarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.ligar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_LigarActionPerformed

    private void jToggleButton_AV_DesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_DesligarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.desligar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_DesligarActionPerformed

    private void jToggleButton_AV_EsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_EsquerdaActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.aviao_puxar_manche_esquerda()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_EsquerdaActionPerformed

    private void jToggleButton_AV_DireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_DireitaActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.aviao_puxar_manche_direita()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_DireitaActionPerformed

    private void jToggleButton_AV_EmpurrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_EmpurrarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.aviao_empurrar_manche_frente()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_EmpurrarActionPerformed

    private void jToggleButton_AV_PuxarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_PuxarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.aviao_puxar_manche_tras()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_PuxarActionPerformed

    private void jToggleButton_AV_AcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_AcelerarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.aviao_empurrar_alavanca_acelerar()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_AcelerarActionPerformed

    private void jToggleButton_AV_FreiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AV_FreiarActionPerformed
        // TODO add your handling code here:
        try {
            
           Aviao dados_aviao = new Aviao();
           
           String entrada = "";
           
           if (jRadioButton_Aviao.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_aviao.setNome_do_veiculo(entrada);
            
           String saida_dados_aviao = "Veiculo \n";
           saida_dados_aviao += "Tipo: " + dados_aviao.getTipoDoVeiculo()+ "\n";
           saida_dados_aviao += "Nome: " + dados_aviao.getNome_do_veiculo()+ "\n";
           saida_dados_aviao += "Ação: " + dados_aviao.aviao_puxar_alavanca_freiar()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_aviao);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_AV_FreiarActionPerformed

    private void jToggleButton_B_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_EntrarActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.entrar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_EntrarActionPerformed

    private void jToggleButton_B_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_SairActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.sair_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_SairActionPerformed

    private void jToggleButton_B_LigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_LigarActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.ligar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_LigarActionPerformed

    private void jToggleButton_B_DesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_DesligarActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.desligar_veiculo()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_DesligarActionPerformed

    private void jToggleButton_B_EsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_EsquerdaActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.barco_virando_timao_esquerda()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_EsquerdaActionPerformed

    private void jToggleButton_B_DireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_DireitaActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.barco_virando_timao_direita()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_DireitaActionPerformed

    private void jToggleButton_B_AcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_AcelerarActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.barco_empurrar_alavanca_acelerar()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_AcelerarActionPerformed

    private void jToggleButton_B_FreiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_B_FreiarActionPerformed
        // TODO add your handling code here:
        try {
            
           Barco dados_barco = new Barco();
           
           String entrada = "";
           
           if (jRadioButton_Barco.isSelected()){
               
           //nome
           entrada = jTextField_Nome.getText();
           dados_barco.setNome_do_veiculo(entrada);
            
           String saida_dados_barco = "Veiculo \n";
           saida_dados_barco += "Tipo: " + dados_barco.getTipoDoVeiculo()+ "\n";
           saida_dados_barco += "Nome: " + dados_barco.getNome_do_veiculo()+ "\n";
           saida_dados_barco += "Ação: " + dados_barco.barco_puxar_alavanca_freiar()+"\n";
           
           jTextArea_Resultado.setText(saida_dados_barco);
           }
               
               
           
           } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jToggleButton_B_FreiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Automovel;
    private javax.swing.JPanel jPanel_Aviao;
    private javax.swing.JPanel jPanel_Barco;
    private javax.swing.JPanel jPanel_Vazio;
    private javax.swing.JRadioButton jRadioButton_Automovel;
    private javax.swing.JRadioButton jRadioButton_Aviao;
    private javax.swing.JRadioButton jRadioButton_Barco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Resultado;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JToggleButton jToggleButton_AV_Acelerar;
    private javax.swing.JToggleButton jToggleButton_AV_Desligar;
    private javax.swing.JToggleButton jToggleButton_AV_Direita;
    private javax.swing.JToggleButton jToggleButton_AV_Empurrar;
    private javax.swing.JToggleButton jToggleButton_AV_Entrar;
    private javax.swing.JToggleButton jToggleButton_AV_Esquerda;
    private javax.swing.JToggleButton jToggleButton_AV_Freiar;
    private javax.swing.JToggleButton jToggleButton_AV_Ligar;
    private javax.swing.JToggleButton jToggleButton_AV_Puxar;
    private javax.swing.JToggleButton jToggleButton_AV_Sair;
    private javax.swing.JToggleButton jToggleButton_A_Acelerar;
    private javax.swing.JToggleButton jToggleButton_A_Desligar;
    private javax.swing.JToggleButton jToggleButton_A_Direita;
    private javax.swing.JToggleButton jToggleButton_A_Entrar;
    private javax.swing.JToggleButton jToggleButton_A_Esquerda;
    private javax.swing.JToggleButton jToggleButton_A_Freiar;
    private javax.swing.JToggleButton jToggleButton_A_Ligar;
    private javax.swing.JToggleButton jToggleButton_A_Sair;
    private javax.swing.JToggleButton jToggleButton_B_Acelerar;
    private javax.swing.JToggleButton jToggleButton_B_Desligar;
    private javax.swing.JToggleButton jToggleButton_B_Direita;
    private javax.swing.JToggleButton jToggleButton_B_Entrar;
    private javax.swing.JToggleButton jToggleButton_B_Esquerda;
    private javax.swing.JToggleButton jToggleButton_B_Freiar;
    private javax.swing.JToggleButton jToggleButton_B_Ligar;
    private javax.swing.JToggleButton jToggleButton_B_Sair;
    // End of variables declaration//GEN-END:variables
}
